version: '3'

services:
  web:
    build: .
    command: ./wait-for-dbs.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
      - db_mysql
      - db_mongo
      - db_cassandra




  # ----------------
  # Databases
  # ----------------
  db_postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"

  db_mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

  db_mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: mongo_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"



  # ----------------
  # Database Admin UIs
  # ----------------
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db_postgres

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db_mysql
      PMA_USER: mysql_user
      PMA_PASSWORD: mysql_pass
    ports:
      - "8081:80"
    depends_on:
      - db_mysql

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: db_mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8082:8081"
    depends_on:
      - db_mongo


  db_cassandra:
    image: cassandra:5
    ports:
      - "9042:9042"


#
#🌐 Access after running docker compose up --build
#
#Django: 👉 http://localhost:8000
#
#pgAdmin (Postgres UI): 👉 http://localhost:5050 (login admin@admin.com / admin)
#
#phpMyAdmin (MySQL UI): 👉 http://localhost:8081
#
#Mongo Express (MongoDB UI): 👉 http://localhost:8082
#
#⚡ For Cassandra, since UI is weak, just use:
#
#docker exec -it <cassandra_container_id> cqlsh