version: "3.9"

services:
  web:
    build:
      context: .        # folder with Dockerfile & requirements.txt
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - static_volume:/app/staticfiles   # Django STATIC_ROOT
      - media_volume:/app/media          # Django MEDIA_ROOT
#    ports:
#      - "8000:8000"  # optional, for direct access (or just use Nginx)
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  web1:
    build:
      context: .        # folder with Dockerfile & requirements.txt
      dockerfile: Dockerfile
    container_name: django_app_2
    volumes:
      - static_volume:/app/staticfiles   # Django STATIC_ROOT
      - media_volume:/app/media          # Django MEDIA_ROOT
#    ports:
#      - "8000:8000"  # optional, for direct access (or just use Nginx)
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  web2:
    build:
      context: .        # folder with Dockerfile & requirements.txt
      dockerfile: Dockerfile
    container_name: django_app_3
    volumes:
      - static_volume:/app/staticfiles   # Django STATIC_ROOT
      - media_volume:/app/media          # Django MEDIA_ROOT
#    ports:
#      - "8000:8000"  # optional, for direct access (or just use Nginx)
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static   # map to Nginx static path
      - media_volume:/media     # map to Nginx media path
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"   # Access pgAdmin on localhost:8080
    depends_on:
      - db


volumes:
  postgres_data:
  static_volume:
  media_volume:
